apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: hospital-app
type: Opaque
data:
  # Base64 encoded values for sensitive configurations
  # 'securepassword123' base64 is c2VjdXJlcGFzc3dvcmQxMjM=
  postgres-password: c2VjdXJlcGFzc3dvcmQxMjM=
